// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Manager.proto

/*
Package opencopilot is a generated protocol buffer package.

It is generated from these files:
	Manager.proto

It has these top-level messages:
	ManagerStatusRequest
	ConfigureRequest
	ManagerStatus
*/
package opencopilot

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ManagerStatusRequest struct {
}

func (m *ManagerStatusRequest) Reset()                    { *m = ManagerStatusRequest{} }
func (m *ManagerStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*ManagerStatusRequest) ProtoMessage()               {}
func (*ManagerStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ConfigureRequest struct {
	Config string `protobuf:"bytes,1,opt,name=config" json:"config,omitempty"`
}

func (m *ConfigureRequest) Reset()                    { *m = ConfigureRequest{} }
func (m *ConfigureRequest) String() string            { return proto.CompactTextString(m) }
func (*ConfigureRequest) ProtoMessage()               {}
func (*ConfigureRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ConfigureRequest) GetConfig() string {
	if m != nil {
		return m.Config
	}
	return ""
}

type ManagerStatus struct {
}

func (m *ManagerStatus) Reset()                    { *m = ManagerStatus{} }
func (m *ManagerStatus) String() string            { return proto.CompactTextString(m) }
func (*ManagerStatus) ProtoMessage()               {}
func (*ManagerStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*ManagerStatusRequest)(nil), "opencopilot.ManagerStatusRequest")
	proto.RegisterType((*ConfigureRequest)(nil), "opencopilot.ConfigureRequest")
	proto.RegisterType((*ManagerStatus)(nil), "opencopilot.ManagerStatus")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Manager service

type ManagerClient interface {
	GetStatus(ctx context.Context, in *ManagerStatusRequest, opts ...grpc.CallOption) (*ManagerStatus, error)
	Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ManagerStatus, error)
}

type managerClient struct {
	cc *grpc.ClientConn
}

func NewManagerClient(cc *grpc.ClientConn) ManagerClient {
	return &managerClient{cc}
}

func (c *managerClient) GetStatus(ctx context.Context, in *ManagerStatusRequest, opts ...grpc.CallOption) (*ManagerStatus, error) {
	out := new(ManagerStatus)
	err := grpc.Invoke(ctx, "/opencopilot.Manager/GetStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerClient) Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ManagerStatus, error) {
	out := new(ManagerStatus)
	err := grpc.Invoke(ctx, "/opencopilot.Manager/Configure", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Manager service

type ManagerServer interface {
	GetStatus(context.Context, *ManagerStatusRequest) (*ManagerStatus, error)
	Configure(context.Context, *ConfigureRequest) (*ManagerStatus, error)
}

func RegisterManagerServer(s *grpc.Server, srv ManagerServer) {
	s.RegisterService(&_Manager_serviceDesc, srv)
}

func _Manager_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManagerStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/opencopilot.Manager/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).GetStatus(ctx, req.(*ManagerStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Manager_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/opencopilot.Manager/Configure",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServer).Configure(ctx, req.(*ConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Manager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "opencopilot.Manager",
	HandlerType: (*ManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _Manager_GetStatus_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _Manager_Configure_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Manager.proto",
}

func init() { proto.RegisterFile("Manager.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xf5, 0x4d, 0xcc, 0x4b,
	0x4c, 0x4f, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xce, 0x2f, 0x48, 0xcd, 0x4b,
	0xce, 0x2f, 0xc8, 0xcc, 0xc9, 0x2f, 0x51, 0x12, 0xe3, 0x12, 0x81, 0xca, 0x06, 0x97, 0x24, 0x96,
	0x94, 0x16, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x28, 0x69, 0x71, 0x09, 0x38, 0xe7, 0xe7,
	0xa5, 0x65, 0xa6, 0x97, 0x16, 0xa5, 0x42, 0xc5, 0x84, 0xc4, 0xb8, 0xd8, 0x92, 0xc1, 0x62, 0x12,
	0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x50, 0x9e, 0x12, 0x3f, 0xdc, 0x06, 0x88, 0x19, 0x46, 0x0b,
	0x19, 0xb9, 0xd8, 0xa1, 0x22, 0x42, 0x3e, 0x5c, 0x9c, 0xee, 0xa9, 0x25, 0x10, 0x09, 0x21, 0x45,
	0x3d, 0x24, 0xbb, 0xf5, 0xb0, 0x59, 0x2c, 0x25, 0x85, 0x5b, 0x89, 0x12, 0x83, 0x90, 0x07, 0x17,
	0x27, 0xdc, 0x59, 0x42, 0xb2, 0x28, 0x4a, 0xd1, 0x9d, 0x8b, 0xdf, 0xa4, 0x24, 0x36, 0x70, 0x60,
	0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x84, 0x55, 0x61, 0xce, 0x1d, 0x01, 0x00, 0x00,
}
